name: CICD
on:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI/CD
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust v1.73.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.73.0"
          override: true
          components: rustfmt, clippy

      - name: Lint
        run: cargo clippy -p api_documentation -p api_implementation

      - name: Run tests
        run: cargo test

      - name: Setup fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build and Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
