name: CICD
on:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI/CD
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust v1.73.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.73.0"
          override: true
          components: rustfmt, clippy

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Lint
        run: |
          cargo fmt --all -- --check
          ./script/lint.sh

      - name: Install cargo check tools
        run: |
          cargo install --locked cargo-audit || true
          cargo install --locked cargo-pants || true

      - name: Check (Silenced for now)
        run: |
          cargo audit || true
          cargo pants || true

      - name: Run tests
        run: cargo test

      - name: Check if new migration changes
        id: migration-changes
        uses: tj-actions/changed-files@v40
        with:
          files: |
            migrations/**/*.rs

      - name: Run Migrations
        if: steps.migration-changes.outputs.test_any_changed == 'true'
        run: cargo run -p migration
        env:
          SURREALDB_URL: ${{ secrets.SURREALDB_URL }}
          SURREALDB_NAMESPACE: ${{ secrets.SURREALDB_NAMESPACE }}
          SURREALDB_DATABASE: ${{ secrets.SURREALDB_DATABASE }}
          SURREALDB_USERNAME: ${{ secrets.SURREALDB_USERNAME }}
          SURREALDB_PASSWORD: ${{ secrets.SURREALDB_PASSWORD }}

      - name: Setup fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build and Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
